ros_release: 'hydro'
ros_user: 'ronexserial'
ros_user_comment: 'RoNeX Program And Test'
ros_user_password: "password"
ros_user_email: 'software@shadowrobot.com'
ros_user_background: "files/images/ronex.jpg"
monospace_font: "Ubuntu Mono 11"
ros_packages:
  - sr-ronex
shadow_opt: /opt/shadow
ronexserial:
  installdir: "{{ shadow_opt }}/sr-ronex-serial-db"
  repo: git@github.com:shadow-robot/sr-ronex-serial-db
  dbname: ronexserial
  dbuser: ronexserial
  dbpassword: password
  dbhost: localhost
  dbport: 5432
shared_folder: "{{ronexserial.installdir}}"

