---
- name: Test for KCL remote
  command: git remote show kcl
           chdir={{ ros_workspace }}/src/sr_grasp_stabilisation
  ignore_errors: True
  register: kcl_remote_test

- name: Add KCL remote
  become: yes
  become_method: sudo
  become_user: "{{ ros_user }}"
  command: git remote add kcl git@github.com:shadow-robot/kcl-gsc-source-code.git
           chdir={{ ros_workspace }}/src/sr_grasp_stabilisation
  when: kcl_remote_test|failed

- name: Fix repo perms
  file: path={{ ros_workspace }}/src/sr_grasp_stabilisation
        owner={{ros_user}} group={{ros_group}}
        recurse=yes
  when: kcl_remote_test|failed

- name: Normal user access for ethercat loop
  become: yes
  command: setcap cap_sys_nice,cap_ipc_lock,cap_net_raw,cap_net_admin=eip /opt/ros/hydro/lib/pr2_ethercat/pr2_ethercat

- name: Setcap nice
  become: yes
  command: setcap cap_sys_nice=eip /usr/bin/nice
