---
- name: Install packages
  apt: name={{item}}
  with_items:
    - python-pip
    - ccze
    - sqlite3
    - libpq-dev
    - python-dev
    - postgresql
    - postgresql-contrib
    - python-psycopg2

- name: Install Django 1.5
  shell: pip install Django==1.5

- name: Create shadow opt dir
  file: state=directory path={{shadow_opt}} owner={{ros_user}} group=ros

- name: Fix perms
  file: path={{shadow_opt}} recurse=yes owner={{ros_user}} group=ros

- name: Repo status
  git: repo={{ronexserial.repo}} dest="{{ronexserial.installdir}}" accept_hostkey=True update=no
  register: repo
  sudo: yes
  # changed: [ronexserial] => {"after": "cfa60a0f538acfb9bd683ab1904a71baff0ed833", "before": null, "changed": true}

# Only do this if no repo there, we don't want to destroy work
# TODO: Would be nice to check the state, update if clean.
- name: Checkout the ronex serial db repository
  git: repo={{ronexserial.repo}} dest="{{ronexserial.installdir}}" accept_hostkey=True
  sudo: yes
  when: not repo.before

- name: Fix perms
  file: path={{ronexserial.installdir}} recurse=yes owner={{ros_user}} group=ros

# This makes the eeprom command line tool we need for programming
- name: Build SOEM
  shell: bash -c "source {{ronexserial.installdir}}/SOEM1.3.0/setup.sh linux && make all"
    chdir="{{ronexserial.installdir}}/SOEM1.3.0"
  sudo: yes
  sudo_user: "{{ros_user}}"

- name: Create ~{{ros_user}}/logs dir
  file: state=directory path=~{{ros_user}}/logs owner={{ros_user}} group=ros

# So we can run without sudo and access the ethercat
- name: Setup soem for normal user
  shell: "setcap cap_sys_nice,cap_ipc_lock,cap_net_raw,cap_net_admin=eip {{ronexserial.installdir}}/ronexserial/bin/eepromtool"

# creates the cluster if it's not yet initialised - ignores the errors if it exists
- name: Create postgres cluster
  sudo: yes
  shell: pg_createcluster 9.3 main --start
  ignore_errors: yes

- name: Create postgresql database
  sudo: yes
  sudo_user: postgres
  postgresql_db: name={{ronexserial.dbname}}

- name: Ensure user has access to database
  sudo: yes
  sudo_user: postgres
  postgresql_user:
    db={{ronexserial.dbname}}
    name={{ronexserial.dbuser}}
    password={{ronexserial.dbpassword}}
    priv=ALL

- name: Ensure user does not have unnecessary privilege
  sudo: yes
  sudo_user: postgres
  postgresql_user: name={{ronexserial.dbuser}}
    role_attr_flags=NOSUPERUSER,NOCREATEDB

# XXX - Need something better than this for live install
# http://www.postgresql.org/docs/current/static/libpq-pgpass.html
- name: Allow user passwordless login
  lineinfile:
    dest=~{{ros_user}}/.pgpass
    line="{{ronexserial.dbhost}}:{{ronexserial.dbport}}:{{ronexserial.dbname}}:{{ronexserial.dbuser}}:{{ronexserial.dbpassword}}"
    state=present
    create=yes
    owner={{ros_user}}
    mode=0600

- name: Generate dbsettings.py
  template: src=dbsettings.py.j2
    dest="{{ronexserial.installdir}}/ronexserial/ronexserial/dbsettings.py"
    owner={{ros_user}}
    mode=0644

- name: Syncdb
  command: python manage.py syncdb --noinput
    chdir={{ronexserial.installdir}}/ronexserial

# For some reason syncdb wont load this as model data, so we fudge it here.
# This is for the admin user that syncdb prompts for when run as a user.
- name: Boot strap auth admin user
  sudo: yes
  sudo_user: "{{ ros_user }}"
  shell: "cat {{ronexserial.installdir}}/ronexserial/serials/sql/auth.sql | python manage.py dbshell chdir={{ronexserial.installdir}}/ronexserial"

- name: Create autostart directory
  file: state=directory path="~{{ros_user}}/.config/autostart" owner={{ros_user}} group=ros

- name: Start server at login
  file: state=link
    src="~{{ros_user}}/Desktop/FlashRonex.desktop"
    dest="~{{ros_user}}/.config/autostart/FlashRonex.desktop"
    force=yes

- name: Start webui at login
  file: state=link
    src="~{{ros_user}}/Desktop/FlashRonexWebUi.desktop"
    dest="~{{ros_user}}/.config/autostart/FlashRonexWebUi.desktop"
    force=yes
