- name: Copy icons to /usr/local/share/icons
  copy: src="files/icons" dest="/usr/local/share"
  become: yes
  become_user: "{{ros_user}}"

- name: Install home directory files from {{ros_user_home_files}}
  copy: src="{{ros_user_home_files}}/" dest="~{{ros_user}}/" owner={{ros_user}} group={{ros_group}}
  when: ros_user_home_files|default("") != ""
  become: yes
  become_user: "{{ros_user}}"

- name: Fix desktop icon path
  replace:
    dest: "~{{ros_user}}/Desktop/Start Hand.desktop"
    regexp: '/home/hand_demo/hydro_ws'
    replace: "{{ros_workspace}}"

- name: Make desktop icon path absolute
  replace:
    dest: "~{{ros_user}}/Desktop/Start Hand.desktop"
    regexp: "~{{ros_user}}"
    replace: "/home/{{ros_user}}"
  
- name: Set executable bit for icons
  shell: "find ~{{ros_user}}/Desktop/*.desktop -exec chmod +x {} +"
  become: yes
  become_user: "{{ros_user}}"
