---
# Defaults for python style_check

linter_disable: "--disable=C0112,C0114,C0115,C0116,R0903,R0904,W9005,W9006,W9008,W9010,W9011,W9012,W9013,W9014,W9015,W9016,R0801,W0717,C1901,C2001,W0141,R0902,R0913,R0916,W0703,C0413,C0415,C0200,C0201,R1715,R1716,R1718,E0401,E0611,W0511"