---
# Playbook for Local CI init specific code

- name: check if local_repo_dir variable was set by build server
  fail: msg="Variable local_repo_dir was not set by CI server"
  when: local_repo_dir is not defined

- name: check if local_test_dir variable was set by build server
  fail: msg="Variable local_test_dir was not set by CI server"
  when: local_test_dir is not defined

- name: check if local_code_coverage_dir variable was set by build server
  fail: msg="Variable local_code_coverage_dir was not set by CI server"
  when: local_code_coverage_dir is not defined

- name: check if local_benchmarking_dir variable was set by build server
  fail: msg="Variable local_benchmarking_dir was not set by CI server"
  when: local_benchmarking_dir is not defined

- name: Set ros_workspace
  set_fact:
    ros_workspace: "{{ansible_env.HOME}}/workspace"

- name: Set upgrade_all_packages
  set_fact:
    upgrade_all_packages: no

- name: Set repository source code path
  set_fact:
    repo_sources_path: "{{ros_workspace}}/src/{{local_repo_dir}}"

- name: Remove source directory in case of caching
  shell: bash -c "rm -rf {{repo_sources_path}}"

- name: Create directory again
  file: state=directory path={{repo_sources_path}}

- name: Copy source directory from host machine
  shell: bash -c "shopt -s dotglob && cp -r {{local_repo_dir}}/* {{repo_sources_path}}"

- name: Remove line from rosdep package cache
  lineinfile: dest=/etc/ros/rosdep/sources.list.d/20-default.list state=absent line="yaml file://{{repo_sources_path}}/local_custom_rosdep.yaml"

- name: Set is_pull_request
  set_fact:
    is_pull_request: "no"

- name: Set test_results_dir
  set_fact:
    test_results_dir: "{{local_test_dir}}"

- name: Set code_coverage_results_dir
  set_fact:
    code_coverage_results_dir: "{{local_code_coverage_dir}}"

- name: Set benchmarking_results_dir
  set_fact:
    benchmarking_results_dir: "{{local_benchmarking_dir}}"

- name: Create tests directory
  file: state=directory path={{test_results_dir}}

- name: Clean tests results directory in case of failure during cache build
  shell: bash -c "rm -rf {{test_results_dir}}/*"

- name: Create coverage directory
  file: state=directory path={{code_coverage_results_dir}}

- name: Clean coverage results directory in case of failure during cached build
  shell: bash -c "rm -rf {{code_coverage_results_dir}}/*"

- name: Create benchmarking directory
  file: state=directory path={{benchmarking_results_dir}}

