---
# tasks file for glassbot
# Note that ubuntu_desktop, ros_install, ros_user and ros_workspace will have
# alredady been run, see meta/main.yml

# Remove the now unnecessary ros_build space (it was necessary to use ar_pose)
- name: Remove rosbuild workspace dir
  file: state=absent path={{ros_build_workspace}}
  become: yes
  become_method: sudo
  become_user: root
  sudo_user: "{{ros_user}}"

# Link the index page to rosbridge
- name: Remove index.html
  file: state=absent path=/var/www/index.html

- name: Link glassbot website for apache
  file: state=link
    src={{ros_workspace}}/src/glassbot/glassbot_game/html/index.html
    dest=/var/www/index.html
    force=yes
  notify:
    - restart apache2
