version: 0.2

env:
  shell: bash
  variables:
     branch: SP-263_add_network_tools
     image: build-tools
     tag: focal-noetic
     dockerfile_folder: docker/ros/noetic/
  exported-variables:
     - branch
     - image
     - tag
     - dockerfile_folder
phases:
  install:
    runtime-versions:
      docker: 19
  build:
    commands:
      - awscli_v1_executable=$(which aws)
      - rm $awscli_v1_executable
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - unzip awscliv2.zip
      - ./aws/install
      - git checkout $branch
      - cd $dockerfile_folder
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/shadowrobot
      - docker build -t $image .
      - docker tag $image:latest public.ecr.aws/shadowrobot/$image:$tag
      - docker push public.ecr.aws/shadowrobot/$image:$tag
      - comm -13 <(aws ecr-public describe-image-tags --repository-name $image --region us-east-1 --output text | awk '{print $3}' | tr " " "\n" | sort -u) <(aws ecr-public describe-images --repository-name $image --region us-east-1 --output text | awk '{print $2}' | tr " " "\n" | sort -u) >> ids_to_delete.txt
      - ids_to_delete=$(sed 's/^/imageDigest=/' ids_to_delete.txt)
      - if [[ -s ids_to_delete.txt ]]; then aws ecr-public batch-delete-image --repository-name $image --region us-east-1 --image-ids $ids_to_delete --output text; fi
